#!/bin/bash

ps -e | grep gunicorn | while read -r proc ; do
    echo "Kill process $proc?"
done


read -p "Enter Y to continue or any other button to exit" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
kill $(ps -e | grep gunicorn | awk '{print $1}')


echo "starting gunicon on localhost:8000"
read -p "Enter Y to continue or any other button to exit" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

source env/bin/activate
nohup gunicorn --bind 127.0.0.1:8000 --workers 2 metalacc.wsgi & disown
