# Generated by Django 3.0.8 on 2020-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200711_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='flerrp', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
