# Generated by Django 3.0.8 on 2020-07-12 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'name'), ('user', 'number')},
        ),
    ]
