# Generated by Django 3.0.8 on 2020-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200712_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='object_limit_accounts',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
