# Generated by Django 3.0.8 on 2020-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200712_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_closing_entry',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
