# Generated by Django 3.0.8 on 2020-07-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_journalentry_is_closing_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryline',
            name='type',
            field=models.CharField(choices=[('d', 'Debit'), ('c', 'Credit')], max_length=1),
        ),
    ]
