# Generated by Django 3.0.8 on 2020-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200728_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='display_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
