# Generated by Django 3.0.8 on 2020-09-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_journalentry_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='open_links_in_new_tabs',
            field=models.BooleanField(default=False),
        ),
    ]
