# Generated by Django 3.0.8 on 2020-09-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_open_links_in_new_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_operating',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
