# Generated by Django 3.0.8 on 2020-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_account_is_operating'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tag',
            field=models.CharField(blank=True, choices=[('div', 'Dividends'), ('cogs', 'Cost of Goods Sold')], default=None, max_length=5, null=True),
        ),
    ]
