# Generated by Django 3.0.8 on 2020-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200919_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='object_limit_accounts',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='object_limit_companies',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='object_limit_entries_per_period',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='object_limit_periods_per_company',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
