# Generated by Django 3.0.8 on 2020-09-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200920_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowWorksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('version_hash', models.CharField(max_length=40)),
                ('data', models.TextField(blank=True, default=None, null=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Period')),
            ],
        ),
    ]
