# Generated by Django 3.0.8 on 2020-09-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cashflowworksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='object_limit_entries_per_period',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
