# Generated by Django 3.0.8 on 2020-09-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200923_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_finger_print_str',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
