# Generated by Django 3.0.8 on 2020-09-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_company_user_finger_print_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_hash',
            field=models.CharField(default='aaaaaaaaaaaaaaaaaaaaaaaaaa', max_length=50),
            preserve_default=False,
        ),
    ]
