# Generated by Django 3.0.8 on 2020-09-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_userprofile_user_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_hash',
        ),
    ]
