# Generated by Django 3.0.8 on 2020-09-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_userprofile_user_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='memo',
            field=models.CharField(blank=True, default=None, max_length=79, null=True),
        ),
    ]
