# Generated by Django 3.0.8 on 2020-10-18 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_contactussubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactussubmission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 19, 55, 20, 355717, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
